/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tcc.telas;

import br.com.tcc.dal.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mateus da Cruz
 */
public class Configuracoes extends javax.swing.JInternalFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Gado
     */
    
    public void Fechar(){
                this.dispose();
    }
    
    private void Setar(){
        String sql = "SELECT * FROM usuarios WHERE id = ?";
        try {           
            Login login = new Login();
            pst = conexao.prepareStatement(sql);
            
            pst.setString(1, login.getId());
            rs = pst.executeQuery();
            
            if(rs.next()){
                txt_propriedade.setText(rs.getString("propriedade"));
                txt_email.setText(rs.getString("email"));
                txt_telefone.setText(rs.getString("telefone"));
                txt_senha.setText(rs.getString("senha"));
            }else{
                JOptionPane.showMessageDialog(null, "Houve um erro ao efetuar a operação, tente novamente!");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO:\n" + e);
        }
    }
    
    private void Salvar(){
        String sql = "UPDATE usuarios SET propriedade = ?, email = ?, telefone = ?, senha = ? WHERE id = ?";
        
        try {
            Login login = new Login();
            pst = conexao.prepareStatement(sql);

            pst.setString(1, txt_propriedade.getText());
            pst.setString(2, txt_email.getText());
            pst.setString(3, txt_telefone.getText());
            pst.setString(4, txt_senha.getText());
            pst.setString(5, login.getId());
            
            int Editado = pst.executeUpdate();
            
            if(Editado > 0){
                JOptionPane.showMessageDialog(null, "Editado com sucesso!");
                Setar();
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao editar!");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO: " + e);
        
        }
    }
    
    public Configuracoes() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel = new javax.swing.JDesktopPane();
        btn_login = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        txt_propriedade = new javax.swing.JTextField();
        propriedade = new javax.swing.JLabel();
        txt_senha = new javax.swing.JPasswordField();
        txt_telefone = new javax.swing.JTextField();
        Telefone = new javax.swing.JLabel();
        EMail = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        senha = new javax.swing.JLabel();
        Título1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        Painel.setBackground(new java.awt.Color(204, 204, 204));

        btn_login.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_login.setText("Fechar");
        btn_login.setToolTipText("Fechar");
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        Painel.add(btn_login);
        btn_login.setBounds(680, 550, 90, 23);

        btn_salvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.setToolTipText("Salvar");
        btn_salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        Painel.add(btn_salvar);
        btn_salvar.setBounds(370, 400, 90, 23);

        txt_propriedade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_propriedadeActionPerformed(evt);
            }
        });
        Painel.add(txt_propriedade);
        txt_propriedade.setBounds(180, 260, 210, 30);

        propriedade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        propriedade.setText("Propriedade:");
        Painel.add(propriedade);
        propriedade.setBounds(180, 230, 130, 30);

        txt_senha.setEditable(false);
        Painel.add(txt_senha);
        txt_senha.setBounds(180, 330, 210, 30);

        txt_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefoneActionPerformed(evt);
            }
        });
        Painel.add(txt_telefone);
        txt_telefone.setBounds(450, 260, 210, 30);

        Telefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Telefone.setText("Telefone:");
        Painel.add(Telefone);
        Telefone.setBounds(450, 230, 90, 30);

        EMail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EMail.setText("E-Mail:");
        Painel.add(EMail);
        EMail.setBounds(450, 300, 70, 30);

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        Painel.add(txt_email);
        txt_email.setBounds(450, 330, 210, 30);

        senha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        senha.setText("Senha:");
        Painel.add(senha);
        senha.setBounds(180, 300, 70, 30);

        Título1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Título1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Título1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateus da Cruz\\Desktop\\img app\\employee.png")); // NOI18N
        Título1.setText("Configurações");
        Painel.add(Título1);
        Título1.setBounds(160, 110, 490, 70);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/img/telacinza800x600.png"))); // NOI18N
        Fundo.setToolTipText("");
        Painel.add(Fundo);
        Fundo.setBounds(4, 14, 800, 580);

        getContentPane().add(Painel);
        Painel.setBounds(-10, -20, 800, 600);

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        Setar();
    }//GEN-LAST:event_formInternalFrameOpened

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefoneActionPerformed

    private void txt_propriedadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_propriedadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_propriedadeActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        Salvar();
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EMail;
    private javax.swing.JLabel Fundo;
    public static javax.swing.JDesktopPane Painel;
    private javax.swing.JLabel Telefone;
    private javax.swing.JLabel Título1;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JLabel propriedade;
    private javax.swing.JLabel senha;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_propriedade;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the BrincoTOID
     */

    /**
     * @return the Brinco
     */
}