/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tcc.telas;

import br.com.tcc.dal.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateus da Cruz
 */
public class GadoAdicionar extends javax.swing.JInternalFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form GadoAdicionar
     */

    private static String brincorastreado;
    private static String controleinterno;
    private static String nome;
    private static String raca;
    private static String nascimento;
    private static String peso;
    
    public String getBrincorastreado() {
        return brincorastreado;
    }

    public void setBrincorastreado(String brincorastreado) {
        this.brincorastreado = brincorastreado;
    }

    public String getControleinterno() {
        return controleinterno;
    }

    public void setControleinterno(String controleinterno) {
        this.controleinterno = controleinterno;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getRaca() {
        return raca;
    }

    public void setRaca(String raca) {
        this.raca = raca;
    }
    public void Limpar(){
        campo_brincorastreado.setText("");
        campo_controleinterno.setText("");
        campo_nome.setText("");
        campo_raca.setText("");
    }
    
    private static String idgado;
    private static int idgadoresult;

    public String getId() {
        return idgado;
    }
    
    public void setId(String idgado) {
        this.idgado = idgado;
    }
    
    public int getIdgadoresult() {
        return idgadoresult;
    }
    
    public void setIdgadoresult(int idgadoresult) {
            int idconv = Integer.parseInt(this.idgado);
        this.idgadoresult = idgadoresult + idconv;
    }
    
    public void Adicionar(){
        Login login = new Login();
        
        String sql = "INSERT INTO `gado` (`iduser`, `brincorastreado`, `controleinterno`, `nome`, `raca`, `nascimento`, `peso`, `genero`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        
        try {
            pst = conexao.prepareStatement(sql);
            
            pst.setString(1, login.getId());
            pst.setString(2, campo_brincorastreado.getText());
            pst.setString(3, campo_controleinterno.getText());
            pst.setString(4, campo_nome.getText());
            pst.setString(5, campo_raca.getText());
            pst.setString(6, campo_nascimento.getText());
            pst.setString(7, campo_peso.getText());
            pst.setString(8, (String) caixa_sexo.getSelectedItem());
            
            int Adicionado = pst.executeUpdate();
            
            if(Adicionado > 0){
                JOptionPane.showMessageDialog(null, "Adicionado com sucesso!");
                Limpar();
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao adicionar, tente novamente!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO: " + e);
        }
    }
    
    public void Fechar(){
        this.dispose();
    }
    public GadoAdicionar() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel = new javax.swing.JDesktopPane();
        btn_add = new javax.swing.JButton();
        btn_fechar = new javax.swing.JButton();
        txt_controleinterno = new javax.swing.JLabel();
        txt_brincorastreado = new javax.swing.JLabel();
        txt_raça = new javax.swing.JLabel();
        txt_nome = new javax.swing.JLabel();
        campo_brincorastreado = new javax.swing.JTextField();
        campo_controleinterno = new javax.swing.JTextField();
        campo_nome = new javax.swing.JTextField();
        campo_raca = new javax.swing.JTextField();
        txt_brincorastreado1 = new javax.swing.JLabel();
        campo_nascimento = new javax.swing.JTextField();
        txt_controleinterno1 = new javax.swing.JLabel();
        campo_peso = new javax.swing.JTextField();
        txt_nome1 = new javax.swing.JLabel();
        caixa_sexo = new javax.swing.JComboBox<>();
        Título1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        Painel1 = new javax.swing.JDesktopPane();
        btn_add1 = new javax.swing.JButton();
        btn_fechar1 = new javax.swing.JButton();
        FundoBotão2 = new javax.swing.JLabel();
        FundoBotão3 = new javax.swing.JLabel();
        txt_controleinterno2 = new javax.swing.JLabel();
        txt_brincorastreado2 = new javax.swing.JLabel();
        txt_raça1 = new javax.swing.JLabel();
        txt_nome2 = new javax.swing.JLabel();
        campo_brincorastreado1 = new javax.swing.JTextField();
        campo_controleinterno1 = new javax.swing.JTextField();
        campo_nome1 = new javax.swing.JTextField();
        campo_raca1 = new javax.swing.JTextField();
        txt_brincorastreado3 = new javax.swing.JLabel();
        campo_nascimento1 = new javax.swing.JTextField();
        txt_controleinterno3 = new javax.swing.JLabel();
        campo_peso1 = new javax.swing.JTextField();
        txt_nome3 = new javax.swing.JLabel();
        caixa_sexo1 = new javax.swing.JComboBox<>();
        Título2 = new javax.swing.JLabel();
        Fundo1 = new javax.swing.JLabel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        Painel.setBackground(new java.awt.Color(204, 204, 204));

        btn_add.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/img/file.png"))); // NOI18N
        btn_add.setText("Adicionar");
        btn_add.setToolTipText("Adicionar");
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.setDefaultCapable(false);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        Painel.add(btn_add);
        btn_add.setBounds(380, 420, 140, 33);

        btn_fechar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_fechar.setText("Fechar");
        btn_fechar.setToolTipText("Fechar");
        btn_fechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_fechar.setDefaultCapable(false);
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });
        Painel.add(btn_fechar);
        btn_fechar.setBounds(690, 560, 90, 23);

        txt_controleinterno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_controleinterno.setText("Controle Interno:");
        Painel.add(txt_controleinterno);
        txt_controleinterno.setBounds(70, 260, 106, 17);

        txt_brincorastreado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_brincorastreado.setText("Brinco Rastreado:");
        Painel.add(txt_brincorastreado);
        txt_brincorastreado.setBounds(70, 210, 114, 17);

        txt_raça.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_raça.setText("Raça:");
        Painel.add(txt_raça);
        txt_raça.setBounds(160, 360, 40, 17);

        txt_nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_nome.setText("Nome:");
        Painel.add(txt_nome);
        txt_nome.setBounds(150, 310, 50, 17);

        campo_brincorastreado.setToolTipText("");
        campo_brincorastreado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_brincorastreadoActionPerformed(evt);
            }
        });
        Painel.add(campo_brincorastreado);
        campo_brincorastreado.setBounds(210, 200, 170, 30);
        Painel.add(campo_controleinterno);
        campo_controleinterno.setBounds(210, 250, 170, 30);
        Painel.add(campo_nome);
        campo_nome.setBounds(210, 300, 170, 30);
        Painel.add(campo_raca);
        campo_raca.setBounds(210, 350, 170, 30);

        txt_brincorastreado1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_brincorastreado1.setText("Data De Nascimento:");
        Painel.add(txt_brincorastreado1);
        txt_brincorastreado1.setBounds(400, 210, 150, 17);

        campo_nascimento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campo_nascimento.setText("DD/MM/AAAA");
        campo_nascimento.setToolTipText("");
        campo_nascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nascimentoActionPerformed(evt);
            }
        });
        Painel.add(campo_nascimento);
        campo_nascimento.setBounds(560, 200, 170, 30);

        txt_controleinterno1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_controleinterno1.setText("Peso:");
        Painel.add(txt_controleinterno1);
        txt_controleinterno1.setBounds(510, 260, 36, 17);
        Painel.add(campo_peso);
        campo_peso.setBounds(560, 250, 170, 30);

        txt_nome1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_nome1.setText("Sexo:");
        Painel.add(txt_nome1);
        txt_nome1.setBounds(510, 310, 40, 17);

        caixa_sexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        caixa_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Macho", "Fêmea" }));
        Painel.add(caixa_sexo);
        caixa_sexo.setBounds(560, 300, 170, 30);

        Título1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Título1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Título1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/img/logoboi.png"))); // NOI18N
        Título1.setText("Adicionar Gado");
        Painel.add(Título1);
        Título1.setBounds(20, 60, 790, 90);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/img/telacinza800x600.png"))); // NOI18N
        Fundo.setToolTipText("");
        Painel.add(Fundo);
        Fundo.setBounds(4, 24, 800, 580);

        getContentPane().add(Painel);
        Painel.setBounds(-10, -30, 800, 600);

        jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame1formInternalFrameOpened(evt);
            }
        });
        jInternalFrame1.getContentPane().setLayout(null);

        Painel1.setBackground(new java.awt.Color(204, 204, 204));

        btn_add1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_add1.setForeground(new java.awt.Color(255, 255, 255));
        btn_add1.setText("Adicionar");
        btn_add1.setToolTipText("Adicionar");
        btn_add1.setContentAreaFilled(false);
        btn_add1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add1.setDefaultCapable(false);
        btn_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add1ActionPerformed(evt);
            }
        });
        Painel1.add(btn_add1);
        btn_add1.setBounds(600, 280, 90, 23);

        btn_fechar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_fechar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_fechar1.setText("Fechar");
        btn_fechar1.setToolTipText("Fechar");
        btn_fechar1.setContentAreaFilled(false);
        btn_fechar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_fechar1.setDefaultCapable(false);
        btn_fechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fechar1ActionPerformed(evt);
            }
        });
        Painel1.add(btn_fechar1);
        btn_fechar1.setBounds(450, 280, 90, 23);

        FundoBotão2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FundoBotão2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/img/Layout Botão 90x23.png"))); // NOI18N
        Painel1.add(FundoBotão2);
        FundoBotão2.setBounds(600, 280, 90, 23);

        FundoBotão3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FundoBotão3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/img/Layout Botão 90x23.png"))); // NOI18N
        Painel1.add(FundoBotão3);
        FundoBotão3.setBounds(450, 280, 90, 23);

        txt_controleinterno2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_controleinterno2.setForeground(new java.awt.Color(255, 255, 255));
        txt_controleinterno2.setText("Controle Interno:");
        Painel1.add(txt_controleinterno2);
        txt_controleinterno2.setBounds(50, 190, 123, 17);

        txt_brincorastreado2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_brincorastreado2.setForeground(new java.awt.Color(255, 255, 255));
        txt_brincorastreado2.setText("Brinco Rastreado:");
        Painel1.add(txt_brincorastreado2);
        txt_brincorastreado2.setBounds(50, 140, 124, 17);

        txt_raça1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_raça1.setForeground(new java.awt.Color(255, 255, 255));
        txt_raça1.setText("Raça:");
        Painel1.add(txt_raça1);
        txt_raça1.setBounds(140, 290, 40, 17);

        txt_nome2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nome2.setForeground(new java.awt.Color(255, 255, 255));
        txt_nome2.setText("Nome:");
        Painel1.add(txt_nome2);
        txt_nome2.setBounds(130, 240, 50, 17);

        campo_brincorastreado1.setToolTipText("");
        campo_brincorastreado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_brincorastreado1ActionPerformed(evt);
            }
        });
        Painel1.add(campo_brincorastreado1);
        campo_brincorastreado1.setBounds(190, 130, 170, 30);
        Painel1.add(campo_controleinterno1);
        campo_controleinterno1.setBounds(190, 180, 170, 30);
        Painel1.add(campo_nome1);
        campo_nome1.setBounds(190, 230, 170, 30);
        Painel1.add(campo_raca1);
        campo_raca1.setBounds(190, 280, 170, 30);

        txt_brincorastreado3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_brincorastreado3.setForeground(new java.awt.Color(255, 255, 255));
        txt_brincorastreado3.setText("Data De Nascimento:");
        Painel1.add(txt_brincorastreado3);
        txt_brincorastreado3.setBounds(380, 140, 150, 17);

        campo_nascimento1.setText("DD/MM/AAAA");
        campo_nascimento1.setToolTipText("");
        campo_nascimento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nascimento1ActionPerformed(evt);
            }
        });
        Painel1.add(campo_nascimento1);
        campo_nascimento1.setBounds(540, 130, 170, 30);

        txt_controleinterno3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_controleinterno3.setForeground(new java.awt.Color(255, 255, 255));
        txt_controleinterno3.setText("Peso:");
        Painel1.add(txt_controleinterno3);
        txt_controleinterno3.setBounds(490, 190, 38, 17);
        Painel1.add(campo_peso1);
        campo_peso1.setBounds(540, 180, 170, 30);

        txt_nome3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nome3.setForeground(new java.awt.Color(255, 255, 255));
        txt_nome3.setText("Sexo:");
        Painel1.add(txt_nome3);
        txt_nome3.setBounds(490, 240, 40, 17);

        caixa_sexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Macho", "Fêmea" }));
        Painel1.add(caixa_sexo1);
        caixa_sexo1.setBounds(540, 230, 170, 30);

        Título2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Título2.setForeground(new java.awt.Color(255, 255, 255));
        Título2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Título2.setText("Adicionar Gado");
        Painel1.add(Título2);
        Título2.setBounds(10, 30, 790, 60);

        Fundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/img/Fundos TCC.png"))); // NOI18N
        Fundo1.setToolTipText("");
        Painel1.add(Fundo1);
        Fundo1.setBounds(4, 24, 800, 350);

        jInternalFrame1.getContentPane().add(Painel1);
        Painel1.setBounds(-10, -30, 800, 640);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 0, 22, 34);

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        Adicionar();
    }//GEN-LAST:event_btn_addActionPerformed

    private void campo_brincorastreadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_brincorastreadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_brincorastreadoActionPerformed

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed
        // TODO add your handling code here:
        Fechar();
    }//GEN-LAST:event_btn_fecharActionPerformed

    private void campo_nascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nascimentoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add1ActionPerformed

    private void btn_fechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fechar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fechar1ActionPerformed

    private void campo_brincorastreado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_brincorastreado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_brincorastreado1ActionPerformed

    private void campo_nascimento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nascimento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nascimento1ActionPerformed

    private void jInternalFrame1formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame1formInternalFrameOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrame1formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Fundo1;
    private javax.swing.JLabel FundoBotão2;
    private javax.swing.JLabel FundoBotão3;
    private javax.swing.JDesktopPane Painel;
    private javax.swing.JDesktopPane Painel1;
    private javax.swing.JLabel Título1;
    private javax.swing.JLabel Título2;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_add1;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_fechar1;
    public static javax.swing.JComboBox<String> caixa_sexo;
    public static javax.swing.JComboBox<String> caixa_sexo1;
    public static javax.swing.JTextField campo_brincorastreado;
    public static javax.swing.JTextField campo_brincorastreado1;
    public static javax.swing.JTextField campo_controleinterno;
    public static javax.swing.JTextField campo_controleinterno1;
    public static javax.swing.JTextField campo_nascimento;
    public static javax.swing.JTextField campo_nascimento1;
    public static javax.swing.JTextField campo_nome;
    public static javax.swing.JTextField campo_nome1;
    public static javax.swing.JTextField campo_peso;
    public static javax.swing.JTextField campo_peso1;
    public static javax.swing.JTextField campo_raca;
    public static javax.swing.JTextField campo_raca1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel txt_brincorastreado;
    private javax.swing.JLabel txt_brincorastreado1;
    private javax.swing.JLabel txt_brincorastreado2;
    private javax.swing.JLabel txt_brincorastreado3;
    private javax.swing.JLabel txt_controleinterno;
    private javax.swing.JLabel txt_controleinterno1;
    private javax.swing.JLabel txt_controleinterno2;
    private javax.swing.JLabel txt_controleinterno3;
    private javax.swing.JLabel txt_nome;
    private javax.swing.JLabel txt_nome1;
    private javax.swing.JLabel txt_nome2;
    private javax.swing.JLabel txt_nome3;
    private javax.swing.JLabel txt_raça;
    private javax.swing.JLabel txt_raça1;
    // End of variables declaration//GEN-END:variables
}