/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tcc.telas;

import br.com.tcc.dal.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateus da Cruz
 */
public class GadoEditar extends javax.swing.JInternalFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form GadoAdicionar
     */
    
    private static String nome;
    private static String brincorastreado;
    private static String peso;
    private static String raca;
    private static String nascimento;

    public void Limpar(){
        campo_nome.setText("");
        campo_brincorastreado.setText("");
        campo_peso.setText("");
        campo_raca.setText("");
        campo_nascimento.setText("");
    }
    
    public void Setar(){
        campo_nome.setText(getNome());
        campo_brincorastreado.setText(getBrincorastreado());
        campo_peso.setText(getPeso());
        campo_raca.setText(getRaca());
        campo_nascimento.setText(getNascimento());
    }
    
    public void Fechar(){
        this.dispose();
    }
    
    private void Salvar(){
        String sql = "update gado set nome = ?, brincorastreado = ?, peso = ?, raca = ?, nascimento = ? where brincorastreado = ?";
        try {
            Gado gado = new Gado();
            pst = conexao.prepareStatement(sql);

            pst.setString(1, campo_nome.getText());
            pst.setString(2, campo_brincorastreado.getText());
            pst.setString(3, campo_peso.getText());
            pst.setString(4, campo_raca.getText());
            pst.setString(5, campo_nascimento.getText());
            pst.setString(6, campo_brincorastreado.getText());
            
            int Editado = pst.executeUpdate();
            
            if(Editado > 0){
                JOptionPane.showMessageDialog(null, "Editado com sucesso!");
                gado.Consultar();
                this.dispose();
                //gado.Painel.getSelectedFrame().dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao editar!");
            }
            
        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERRO:\n" + e);
        }
    }
    
    public GadoEditar() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel = new javax.swing.JDesktopPane();
        btn_fechar = new javax.swing.JButton();
        txt_brincorastreado = new javax.swing.JLabel();
        txt_raça = new javax.swing.JLabel();
        txt_nome = new javax.swing.JLabel();
        txt_brincorastreado1 = new javax.swing.JLabel();
        campo_nascimento = new javax.swing.JTextField();
        campo_peso = new javax.swing.JTextField();
        txt_controleinterno = new javax.swing.JLabel();
        campo_brincorastreado = new javax.swing.JTextField();
        campo_nome = new javax.swing.JTextField();
        campo_raca = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();
        Título1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        Painel.setBackground(new java.awt.Color(204, 204, 204));

        btn_fechar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_fechar.setText("Fechar");
        btn_fechar.setToolTipText("Fechar");
        btn_fechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });
        Painel.add(btn_fechar);
        btn_fechar.setBounds(700, 550, 80, 23);

        txt_brincorastreado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_brincorastreado.setText("Brinco Rastreado:");
        Painel.add(txt_brincorastreado);
        txt_brincorastreado.setBounds(190, 270, 114, 17);

        txt_raça.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_raça.setText("Raça:");
        Painel.add(txt_raça);
        txt_raça.setBounds(270, 370, 40, 17);

        txt_nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_nome.setText("Nome:");
        Painel.add(txt_nome);
        txt_nome.setBounds(260, 220, 40, 17);

        txt_brincorastreado1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_brincorastreado1.setText("Data De Nascimento:");
        Painel.add(txt_brincorastreado1);
        txt_brincorastreado1.setBounds(170, 420, 133, 17);

        campo_nascimento.setText("DD/MM/AAAA");
        campo_nascimento.setToolTipText("");
        campo_nascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nascimentoActionPerformed(evt);
            }
        });
        Painel.add(campo_nascimento);
        campo_nascimento.setBounds(320, 410, 230, 30);
        Painel.add(campo_peso);
        campo_peso.setBounds(320, 310, 230, 30);

        txt_controleinterno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_controleinterno.setText("Peso:");
        Painel.add(txt_controleinterno);
        txt_controleinterno.setBounds(270, 320, 36, 17);

        campo_brincorastreado.setEditable(false);
        campo_brincorastreado.setToolTipText("");
        campo_brincorastreado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_brincorastreadoActionPerformed(evt);
            }
        });
        Painel.add(campo_brincorastreado);
        campo_brincorastreado.setBounds(320, 260, 230, 30);
        Painel.add(campo_nome);
        campo_nome.setBounds(320, 210, 230, 30);
        Painel.add(campo_raca);
        campo_raca.setBounds(320, 360, 230, 30);

        btn_salvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/img/file.png"))); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.setToolTipText("Salvar");
        btn_salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        Painel.add(btn_salvar);
        btn_salvar.setBounds(360, 470, 120, 30);

        Título1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Título1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Título1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/img/logoboi.png"))); // NOI18N
        Título1.setText("Editar Gado");
        Painel.add(Título1);
        Título1.setBounds(270, 100, 330, 90);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/img/telacinza800x600.png"))); // NOI18N
        Fundo.setToolTipText("");
        Painel.add(Fundo);
        Fundo.setBounds(4, 14, 810, 600);

        getContentPane().add(Painel);
        Painel.setBounds(-10, -30, 800, 600);

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void campo_brincorastreadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_brincorastreadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_brincorastreadoActionPerformed

    private void campo_nascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nascimentoActionPerformed

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed
        // TODO add your handling code here:
        Fechar();
    }//GEN-LAST:event_btn_fecharActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        Salvar();
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        Setar();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JDesktopPane Painel;
    private javax.swing.JLabel Título1;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_salvar;
    public static javax.swing.JTextField campo_brincorastreado;
    public static javax.swing.JTextField campo_nascimento;
    public static javax.swing.JTextField campo_nome;
    public static javax.swing.JTextField campo_peso;
    public static javax.swing.JTextField campo_raca;
    private javax.swing.JLabel txt_brincorastreado;
    private javax.swing.JLabel txt_brincorastreado1;
    private javax.swing.JLabel txt_controleinterno;
    private javax.swing.JLabel txt_nome;
    private javax.swing.JLabel txt_raça;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the nome
     */
    public static String getNome() {
        return nome;
    }

    /**
     * @param aNome the nome to set
     */
    public static void setNome(String aNome) {
        nome = aNome;
    }

    /**
     * @return the brincorastreado
     */
    public static String getBrincorastreado() {
        return brincorastreado;
    }

    /**
     * @param aBrincorastreado the brincorastreado to set
     */
    public static void setBrincorastreado(String aBrincorastreado) {
        brincorastreado = aBrincorastreado;
    }

    /**
     * @return the peso
     */
    public static String getPeso() {
        return peso;
    }

    /**
     * @param aPeso the peso to set
     */
    public static void setPeso(String aPeso) {
        peso = aPeso;
    }

    /**
     * @return the raca
     */
    public static String getRaca() {
        return raca;
    }

    /**
     * @param aRaca the raca to set
     */
    public static void setRaca(String aRaca) {
        raca = aRaca;
    }

    /**
     * @return the nascimento
     */
    public static String getNascimento() {
        return nascimento;
    }

    /**
     * @param aNascimento the nascimento to set
     */
    public static void setNascimento(String aNascimento) {
        nascimento = aNascimento;
    }
}
