/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tcc.telas;
import br.com.tcc.dal.ModuloConexao;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Mateus da Cruz
 */
public class Login extends javax.swing.JFrame {
        Connection conexao = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
    /**
     * Creates new form Login
     */
    private static String id;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public void Registrar(){
                Registro registro = new Registro();
                registro.setVisible((true));
                this.dispose();
    }
    public void Logar(){
        String sql = "select * from usuarios where propriedade = ? and senha = ?";
        
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txt_propriedade.getText());
            pst.setString(2, txt_senha.getText());
            
            rs = pst.executeQuery();
            
            if(rs.next()){
                this.setId(rs.getString("id"));
                Principal Tela = new Principal();
                Tela.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Usuário ou Senha inválido!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public Login() {
        initComponents();
        /*
        URL caminhoImagem = this.getClass().getResource("favicon.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoImagem);
        setIconImage(iconeTitulo);*/
        conexao = ModuloConexao.conector();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        Título = new javax.swing.JLabel();
        status_servidor = new javax.swing.JLabel();
        status_atual = new javax.swing.JLabel();
        txt_propriedade = new javax.swing.JTextField();
        txt_senha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();
        senha = new javax.swing.JLabel();
        propriedade = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Software Log");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Software Log");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 170, 150, 29);

        Título.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Título.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Título.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/img/logoboi.png"))); // NOI18N
        getContentPane().add(Título);
        Título.setBounds(350, 80, 100, 90);

        status_servidor.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        status_servidor.setText("Status do Servidor:");
        getContentPane().add(status_servidor);
        status_servidor.setBounds(480, 470, 100, 20);

        status_atual.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        status_atual.setText("Offline");
        getContentPane().add(status_atual);
        status_atual.setBounds(570, 470, 40, 20);

        txt_propriedade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_propriedadeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_propriedade);
        txt_propriedade.setBounds(260, 250, 270, 30);
        getContentPane().add(txt_senha);
        txt_senha.setBounds(260, 340, 270, 30);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 410, 120, 30);

        btn_registrar.setBackground(new java.awt.Color(255, 255, 255));
        btn_registrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.setToolTipText("Registrar");
        btn_registrar.setBorder(null);
        btn_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrar);
        btn_registrar.setBounds(410, 410, 120, 30);

        senha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        senha.setText("Senha:");
        getContentPane().add(senha);
        senha.setBounds(260, 310, 70, 30);

        propriedade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        propriedade.setText("Propriedade:");
        getContentPane().add(propriedade);
        propriedade.setBounds(260, 220, 130, 30);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/img/pequenofundocinzaclaro.jpg"))); // NOI18N
        fundo.setToolTipText("");
        getContentPane().add(fundo);
        fundo.setBounds(165, 60, 450, 440);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/img/telacinza.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 810, 580);

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_propriedadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_propriedadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_propriedadeActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // TODO add your handling code here:
        Registrar();
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        URL caminhoImagem = this.getClass().getResource("logoboi.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoImagem);
        setIconImage(iconeTitulo);
        System.out.println(conexao);
        if(conexao != null){
            status_atual.setText("Online");
            //semconexao.setSize(0, 0);
            //status_atual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tcc/icones/dbok.png")));
        }else{
            status_atual.setText("Offline");
            //semconexao.setSize(545, 347);
            JOptionPane.showMessageDialog(null, "Verifique se você está conectado a uma rede ou tente novamente mais tarde!", "Problemas De Conexão", HEIGHT);
            //status_atual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tcc/icones/dberro.png")));
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Logar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Título;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel propriedade;
    private javax.swing.JLabel senha;
    private javax.swing.JLabel status_atual;
    private javax.swing.JLabel status_servidor;
    public static javax.swing.JTextField txt_propriedade;
    public static javax.swing.JPasswordField txt_senha;
    // End of variables declaration//GEN-END:variables

}
